config/routes.rb
Rails.application.routes.draw do
  root to: 'candidates#index'
  resources :candidates do
    member do
      post :vote
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/candidate.rb
class Candidate < ApplicationRecord
  validates :name, :party, :politics, uniqueness: { case_sensitive: false }, presence: true
  has_many :vote_logs, dependent: :destroy

  scope :young_people, -> { where('age < 40') }
  scope :older_than, -> (x) { unscope(:where).where("age > #{x}") }
  default_scope { where('age > 0') }
end

app/models/vote_log.rb
class VoteLog < ApplicationRecord
  belongs_to :candidate, counter_cache: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :exist_user

  def exist_user
    @exist_user ||= Candidate.find_by(id: params[:id])
  end

end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController

  before_action :no_user_redirect, only: [:show]
  before_action :set_candidate, only:[:show, :edit, :update, :destroy, :vote]

  def index
    @candidates = Candidate.all
  end

  def new
    @candidate = Candidate.new
  end

  def create
    @candidate = Candidate.new(candidate_params)
    if @candidate.save
      flash[:notice] = "Welcome to my app #{@candidate.name}"
      redirect_to(candidates_path)
    else
      flash.now[:alert] = "Invalid information"
      render('new')
    end
  end

  def show
  end

  def edit
  end

  def update
    if @candidate.update(candidate_params)
      flash[:notice] = "#{@candidate.name}'s profile is updated"
      redirect_to(candidate_path)
    else
      flash.now[:alert] = "Invalid information"
      render('edit')
    end
  end

  def destroy
    if @candidate.destroy
      flash[:notice] = "#{@candidate.name}'s profile is deleted"
      redirect_to(candidates_path)
    else
      flash.now[:alert] = "Cannot delete #{@candidate.name}'s profile"
      redirect_to(candidate_path)
    end
  end

  def vote
    @candidate.vote_logs.create(ip_address: request.remote_ip)
    VoteMailJob.perform_later
    flash[:notice] = "You have voted to #{@candidate.name}."
    redirect_to(candidates_path)
  end

  private

  def candidate_params
    params.require(:candidate).permit(:name, :party, :age, :politics)
  end

  def no_user_redirect
    unless exist_user
      flash[:alert] = "User Not Found"
      redirect_to(candidates_path)
    end
  end

  def set_candidate
    @candidate = Candidate.find_by(id: params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/candidates/_form.html.erb
<% if candidate.errors.any? %>
  <ul>
  <% candidate.errors.full_messages.each do |msg| %>
    <li class="error-msg">
      <%= msg %>
    </li>
  <% end %>
  </ul>
<% end %>

<%= form_with(model: candidate, local: true) do |f| %>

  <p>
      <%= f.label :name %><br/>
      <%= f.text_field :name, autofocus: true, autocomplete: "name", required: true %>
  </p>
  <p>
      <%= f.label :party %><br/>
      <%= f.text_field :party, placeholder: "Enter your party", required: true %>
  </p>
  <p>
      <%= f.label :age %><br/>
      <%= f.number_field :age, in: 30..70, placeholder: "Enter your age", required: true %>
  </p>
  <p>
      <%= f.label :politics %><br/>
      <%= f.text_area :politics, placeholder: "Write your politics", required: true %>
  </p>
  <p>
      <%= f.submit %>
  </p>

<% end %>
<%= link_to 'return to all candidates', candidates_path, class:"return-link" %>

app/views/candidates/edit.html.erb
<h1>Edit Candidate</h1>

<%= render 'form', candidate: @candidate %>

app/views/candidates/index.html.erb
<h1>All candidates</h1>
<div class="block">
  <table class="profile">
    <thead>
      <tr>
        <th>Vote</th>
        <th>ID</th>
        <th>Name</th>
        <th>Action</th>
        <th></th>
        <th>Votes</th>
      </tr>
    </thead>
    <tbody>
      <% @candidates.each do |candidate| %>
      <tr>
        <td><%= link_to 'Vote', vote_candidate_path(candidate), method: :post %></td>
        <td><%= candidate.id %></td>
        <td><%= link_to candidate.name, candidate_path(candidate) %></td>
        <td><%= link_to 'Edit', edit_candidate_path(candidate) %></td>
        <td><%= link_to 'Delete', candidate_path(candidate), method: :delete, data: { confirm: "Are you sure?" } %></td>
        <td><%= candidate.vote_logs.size %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= link_to 'Add Candidate', new_candidate_path %>

app/views/candidates/new.html.erb
<h1>Add Candidate</h1>

<%= render 'form', candidate: @candidate %>
<%# 將實體變數抽離partial file，讓partial file不必主動去找實體變數，在這裡決定partial file呈現的內容 %>

app/views/candidates/show.html.erb
<h1><%= @candidate.name %>'s Profile</h1>
  <div class="block">
    <table class="profile">
      <thead>
        <tr>
          <th>Party</th>
          <th>Age</th>
          <th>Politics</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= @candidate.party %></td>
          <td><%= @candidate.age %></td>
          <td><%= @candidate.politics %></td>
        </tr>
      </tbody>
    </table>
  </div>
<%= link_to "Edit", edit_candidate_path %>
<%= link_to "Delete", candidate_path(@candidate), method: :delete, data: { confirm: "Are you sure?" } %>
<%= link_to 'All Candidates', candidates_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VoteMe</title>
    <%= favicon_link_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="flash">
      <% if notice %>
        <p class="notice"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert"><%= alert %></p>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>